Mission5/Models/Class.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPWebApp.Models
{
    public class Class
    {
        public double Assignments { get; set; }
        public double Group { get; set; }
        public double Quizzes { get; set; }
        public double Midterm { get; set; }
        public double Final { get; set; }
        public double Intex { get; set; }
   

    }
}

Mission5/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstASPWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPWebApp.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalcView()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult GradeCalcView (Class model)
        {
            return View();
        }
    }
}

Mission5/Views/Blah/GradeCalcView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@model Class;

<h2>Grade Percentage Calculator</h2>
<form method="post">

    <label>Assignments</label>
    <input id="Assignments" asp-for="Assignments" /> <br />
    <label>Group Project</label>
    <input id="Group" asp-for="Group" /> <br />
    <label>Quizzes</label>
    <input id="Quizzes" asp-for="Quizzes" /> <br />
    <label>Midterm Exam</label>
    <input id="Midterm" asp-for="Midterm" /> <br />
    <label>Final Exam</label>
    <input id="Final" asp-for="Final" /> <br />
    <label>INTEX</label>
    <input id="INTEX" asp-for="INTEX" /> <br />
    <input type="submit" value="Calculate" id="calculate" />
</form>
<script src="lib/jQuery/jquery-3.6.3.min.js"></script>
<script src="js/grade_calc.js"></script>

Mission5/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ ViewData["Title"] = "Nato Potato";
}




<h1>Nathan Samuel Wirthlin</h1>
<img src="img/BYUGame.jpeg.JPG" width="400" />
<p>I love watching and playing sports with my friends</p>

<br />
<br />

<h2>Top 3 Jobs</h2>
<ol>
    <li>Business Management Consultant</li>
    <li>Data Analyst </li>
    <li>Database Manager </li>
</ol>



<p id="result"></p>

Mission5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>



<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" type="image/x-icon" href="img\favicon_io\favicon-16x16.png">

    <link href="bootstrap/bootstrap-5.3.0-alpha1-dist/css/bootstrap.css" rel="stylesheet" />
    <link href="css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalcView">Grade Calc</a>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>

<footer>This is the footer</footer>
</html>